CALENDAR_LOCALISATION = "en";
CALENDAR_VIEW_WEEKDAY = "long"; //short or long
CALENDAR_WEEKDAY_EU = true; //
CALENDAR_HIGHDAY = ['4/29/2019','4/30/2019','5/1/2019']; // mm/dd/yyyy

CALENDAR_STAT_ALIENDAY = -1;
CALENDAR_STAT_HIGHDAY = 1;
CALENDAR_STAT_WEEKEND = 2;